import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="px-6 md:px-6 pt-1 pb-24 md:mt-10 md:pb-25 max-w-[700px] m-auto ring-offset-primary">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
